version: '3'

services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
