version: '3.1'

services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    ports:
      - '35432:5432'
    environment:
      POSTGRES_PASSWORD: ponto_ilumeo
