FROM node:18 AS builder

ENV NODE_ENV development

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN apt-get -qy update && apt-get -qy install openssl

RUN yarn 
RUN yarn add @prisma/client

COPY . .

RUN npx prisma generate --schema ./prisma/schema.prisma

EXPOSE 8000

CMD yarn dev
















